language: ruby
before_install: cd forum
rvm:
  - "2.2.3"

env:
  - DB=sqlite

install:
  - bundle install

script:
  - bundle exec rake cucumber features/step_definitions/user_log_in_steps.rb

gemfile:
  - Gemfile

